---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: panoptium-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: panoptium-webhook-service
      namespace: system
      path: /validate-panoptium-io-v1alpha1-panoptiumpolicy
  failurePolicy: Fail
  name: vpanoptiumpolicy.kb.io
  rules:
  - apiGroups:
    - panoptium.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - panoptiumpolicies
  sideEffects: None
