---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - list
  - watch
- apiGroups:
  - panoptium.io
  resources:
  - clusterpanoptiumpolicies
  - panoptiumagentprofiles
  - panoptiumpolicies
  - panoptiumquarantines
  - panoptiumthreatsignatures
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - panoptium.io
  resources:
  - clusterpanoptiumpolicies/finalizers
  - panoptiumagentprofiles/finalizers
  - panoptiumpolicies/finalizers
  - panoptiumquarantines/finalizers
  - panoptiumthreatsignatures/finalizers
  verbs:
  - update
- apiGroups:
  - panoptium.io
  resources:
  - clusterpanoptiumpolicies/status
  - panoptiumagentprofiles/status
  - panoptiumpolicies/status
  - panoptiumquarantines/status
  - panoptiumthreatsignatures/status
  verbs:
  - get
  - patch
  - update
