//go:build !ignore_autogenerated

/*
Copyright 2026 Cloudaura sp. z o.o.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Action) DeepCopyInto(out *Action) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Action.
func (in *Action) DeepCopy() *Action {
	if in == nil {
		return nil
	}
	out := new(Action)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Base64Rule) DeepCopyInto(out *Base64Rule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Base64Rule.
func (in *Base64Rule) DeepCopy() *Base64Rule {
	if in == nil {
		return nil
	}
	out := new(Base64Rule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BaselineSpec) DeepCopyInto(out *BaselineSpec) {
	*out = *in
	if in.ExpectedToolCalls != nil {
		in, out := &in.ExpectedToolCalls, &out.ExpectedToolCalls
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.NormalResourceUsage = in.NormalResourceUsage
	if in.TypicalNetworkDestinations != nil {
		in, out := &in.TypicalNetworkDestinations, &out.TypicalNetworkDestinations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BaselineSpec.
func (in *BaselineSpec) DeepCopy() *BaselineSpec {
	if in == nil {
		return nil
	}
	out := new(BaselineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CELRule) DeepCopyInto(out *CELRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CELRule.
func (in *CELRule) DeepCopy() *CELRule {
	if in == nil {
		return nil
	}
	out := new(CELRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPanoptiumPolicy) DeepCopyInto(out *ClusterPanoptiumPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPanoptiumPolicy.
func (in *ClusterPanoptiumPolicy) DeepCopy() *ClusterPanoptiumPolicy {
	if in == nil {
		return nil
	}
	out := new(ClusterPanoptiumPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterPanoptiumPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPanoptiumPolicyList) DeepCopyInto(out *ClusterPanoptiumPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterPanoptiumPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPanoptiumPolicyList.
func (in *ClusterPanoptiumPolicyList) DeepCopy() *ClusterPanoptiumPolicyList {
	if in == nil {
		return nil
	}
	out := new(ClusterPanoptiumPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterPanoptiumPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPanoptiumPolicySpec) DeepCopyInto(out *ClusterPanoptiumPolicySpec) {
	*out = *in
	in.TargetSelector.DeepCopyInto(&out.TargetSelector)
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]PolicyRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPanoptiumPolicySpec.
func (in *ClusterPanoptiumPolicySpec) DeepCopy() *ClusterPanoptiumPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ClusterPanoptiumPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPanoptiumPolicyStatus) DeepCopyInto(out *ClusterPanoptiumPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPanoptiumPolicyStatus.
func (in *ClusterPanoptiumPolicyStatus) DeepCopy() *ClusterPanoptiumPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterPanoptiumPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DetectionSpec) DeepCopyInto(out *DetectionSpec) {
	*out = *in
	if in.Patterns != nil {
		in, out := &in.Patterns, &out.Patterns
		*out = make([]PatternRule, len(*in))
		copy(*out, *in)
	}
	if in.Entropy != nil {
		in, out := &in.Entropy, &out.Entropy
		*out = new(EntropyRule)
		**out = **in
	}
	if in.Base64 != nil {
		in, out := &in.Base64, &out.Base64
		*out = new(Base64Rule)
		**out = **in
	}
	if in.CEL != nil {
		in, out := &in.CEL, &out.CEL
		*out = make([]CELRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DetectionSpec.
func (in *DetectionSpec) DeepCopy() *DetectionSpec {
	if in == nil {
		return nil
	}
	out := new(DetectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntropyRule) DeepCopyInto(out *EntropyRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntropyRule.
func (in *EntropyRule) DeepCopy() *EntropyRule {
	if in == nil {
		return nil
	}
	out := new(EntropyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventReference) DeepCopyInto(out *EventReference) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventReference.
func (in *EventReference) DeepCopy() *EventReference {
	if in == nil {
		return nil
	}
	out := new(EventReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForensicSnapshotSpec) DeepCopyInto(out *ForensicSnapshotSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForensicSnapshotSpec.
func (in *ForensicSnapshotSpec) DeepCopy() *ForensicSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(ForensicSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanoptiumAgentProfile) DeepCopyInto(out *PanoptiumAgentProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanoptiumAgentProfile.
func (in *PanoptiumAgentProfile) DeepCopy() *PanoptiumAgentProfile {
	if in == nil {
		return nil
	}
	out := new(PanoptiumAgentProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PanoptiumAgentProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanoptiumAgentProfileList) DeepCopyInto(out *PanoptiumAgentProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PanoptiumAgentProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanoptiumAgentProfileList.
func (in *PanoptiumAgentProfileList) DeepCopy() *PanoptiumAgentProfileList {
	if in == nil {
		return nil
	}
	out := new(PanoptiumAgentProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PanoptiumAgentProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanoptiumAgentProfileSpec) DeepCopyInto(out *PanoptiumAgentProfileSpec) {
	*out = *in
	in.AgentSelector.DeepCopyInto(&out.AgentSelector)
	in.Baselines.DeepCopyInto(&out.Baselines)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanoptiumAgentProfileSpec.
func (in *PanoptiumAgentProfileSpec) DeepCopy() *PanoptiumAgentProfileSpec {
	if in == nil {
		return nil
	}
	out := new(PanoptiumAgentProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanoptiumAgentProfileStatus) DeepCopyInto(out *PanoptiumAgentProfileStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastBaselineUpdate != nil {
		in, out := &in.LastBaselineUpdate, &out.LastBaselineUpdate
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanoptiumAgentProfileStatus.
func (in *PanoptiumAgentProfileStatus) DeepCopy() *PanoptiumAgentProfileStatus {
	if in == nil {
		return nil
	}
	out := new(PanoptiumAgentProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanoptiumPolicy) DeepCopyInto(out *PanoptiumPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanoptiumPolicy.
func (in *PanoptiumPolicy) DeepCopy() *PanoptiumPolicy {
	if in == nil {
		return nil
	}
	out := new(PanoptiumPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PanoptiumPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanoptiumPolicyList) DeepCopyInto(out *PanoptiumPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PanoptiumPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanoptiumPolicyList.
func (in *PanoptiumPolicyList) DeepCopy() *PanoptiumPolicyList {
	if in == nil {
		return nil
	}
	out := new(PanoptiumPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PanoptiumPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanoptiumPolicySpec) DeepCopyInto(out *PanoptiumPolicySpec) {
	*out = *in
	in.TargetSelector.DeepCopyInto(&out.TargetSelector)
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]PolicyRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanoptiumPolicySpec.
func (in *PanoptiumPolicySpec) DeepCopy() *PanoptiumPolicySpec {
	if in == nil {
		return nil
	}
	out := new(PanoptiumPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanoptiumPolicyStatus) DeepCopyInto(out *PanoptiumPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanoptiumPolicyStatus.
func (in *PanoptiumPolicyStatus) DeepCopy() *PanoptiumPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(PanoptiumPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanoptiumQuarantine) DeepCopyInto(out *PanoptiumQuarantine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanoptiumQuarantine.
func (in *PanoptiumQuarantine) DeepCopy() *PanoptiumQuarantine {
	if in == nil {
		return nil
	}
	out := new(PanoptiumQuarantine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PanoptiumQuarantine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanoptiumQuarantineList) DeepCopyInto(out *PanoptiumQuarantineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PanoptiumQuarantine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanoptiumQuarantineList.
func (in *PanoptiumQuarantineList) DeepCopy() *PanoptiumQuarantineList {
	if in == nil {
		return nil
	}
	out := new(PanoptiumQuarantineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PanoptiumQuarantineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanoptiumQuarantineSpec) DeepCopyInto(out *PanoptiumQuarantineSpec) {
	*out = *in
	out.Resolution = in.Resolution
	out.ForensicSnapshot = in.ForensicSnapshot
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanoptiumQuarantineSpec.
func (in *PanoptiumQuarantineSpec) DeepCopy() *PanoptiumQuarantineSpec {
	if in == nil {
		return nil
	}
	out := new(PanoptiumQuarantineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanoptiumQuarantineStatus) DeepCopyInto(out *PanoptiumQuarantineStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AppliedNetworkPolicies != nil {
		in, out := &in.AppliedNetworkPolicies, &out.AppliedNetworkPolicies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BPFLSMRules != nil {
		in, out := &in.BPFLSMRules, &out.BPFLSMRules
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TriggeringEventChain != nil {
		in, out := &in.TriggeringEventChain, &out.TriggeringEventChain
		*out = make([]EventReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ContainedAt != nil {
		in, out := &in.ContainedAt, &out.ContainedAt
		*out = (*in).DeepCopy()
	}
	if in.ReleasedAt != nil {
		in, out := &in.ReleasedAt, &out.ReleasedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanoptiumQuarantineStatus.
func (in *PanoptiumQuarantineStatus) DeepCopy() *PanoptiumQuarantineStatus {
	if in == nil {
		return nil
	}
	out := new(PanoptiumQuarantineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanoptiumThreatSignature) DeepCopyInto(out *PanoptiumThreatSignature) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanoptiumThreatSignature.
func (in *PanoptiumThreatSignature) DeepCopy() *PanoptiumThreatSignature {
	if in == nil {
		return nil
	}
	out := new(PanoptiumThreatSignature)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PanoptiumThreatSignature) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanoptiumThreatSignatureList) DeepCopyInto(out *PanoptiumThreatSignatureList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PanoptiumThreatSignature, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanoptiumThreatSignatureList.
func (in *PanoptiumThreatSignatureList) DeepCopy() *PanoptiumThreatSignatureList {
	if in == nil {
		return nil
	}
	out := new(PanoptiumThreatSignatureList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PanoptiumThreatSignatureList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanoptiumThreatSignatureSpec) DeepCopyInto(out *PanoptiumThreatSignatureSpec) {
	*out = *in
	if in.Protocols != nil {
		in, out := &in.Protocols, &out.Protocols
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Detection.DeepCopyInto(&out.Detection)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanoptiumThreatSignatureSpec.
func (in *PanoptiumThreatSignatureSpec) DeepCopy() *PanoptiumThreatSignatureSpec {
	if in == nil {
		return nil
	}
	out := new(PanoptiumThreatSignatureSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PanoptiumThreatSignatureStatus) DeepCopyInto(out *PanoptiumThreatSignatureStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PanoptiumThreatSignatureStatus.
func (in *PanoptiumThreatSignatureStatus) DeepCopy() *PanoptiumThreatSignatureStatus {
	if in == nil {
		return nil
	}
	out := new(PanoptiumThreatSignatureStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatternRule) DeepCopyInto(out *PatternRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatternRule.
func (in *PatternRule) DeepCopy() *PatternRule {
	if in == nil {
		return nil
	}
	out := new(PatternRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyRule) DeepCopyInto(out *PolicyRule) {
	*out = *in
	out.Trigger = in.Trigger
	if in.Predicates != nil {
		in, out := &in.Predicates, &out.Predicates
		*out = make([]Predicate, len(*in))
		copy(*out, *in)
	}
	in.Action.DeepCopyInto(&out.Action)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyRule.
func (in *PolicyRule) DeepCopy() *PolicyRule {
	if in == nil {
		return nil
	}
	out := new(PolicyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Predicate) DeepCopyInto(out *Predicate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Predicate.
func (in *Predicate) DeepCopy() *Predicate {
	if in == nil {
		return nil
	}
	out := new(Predicate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolutionSpec) DeepCopyInto(out *ResolutionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolutionSpec.
func (in *ResolutionSpec) DeepCopy() *ResolutionSpec {
	if in == nil {
		return nil
	}
	out := new(ResolutionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceUsageSpec) DeepCopyInto(out *ResourceUsageSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceUsageSpec.
func (in *ResourceUsageSpec) DeepCopy() *ResourceUsageSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceUsageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Trigger) DeepCopyInto(out *Trigger) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Trigger.
func (in *Trigger) DeepCopy() *Trigger {
	if in == nil {
		return nil
	}
	out := new(Trigger)
	in.DeepCopyInto(out)
	return out
}
