// Copyright 2026 Cloudaura sp. z o.o.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: panoptium/v1/events.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Severity indicates the severity level of a PanoptiumEvent.
type Severity int32

const (
	Severity_INFO     Severity = 0
	Severity_LOW      Severity = 1
	Severity_MEDIUM   Severity = 2
	Severity_HIGH     Severity = 3
	Severity_CRITICAL Severity = 4
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "INFO",
		1: "LOW",
		2: "MEDIUM",
		3: "HIGH",
		4: "CRITICAL",
	}
	Severity_value = map[string]int32{
		"INFO":     0,
		"LOW":      1,
		"MEDIUM":   2,
		"HIGH":     3,
		"CRITICAL": 4,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_panoptium_v1_events_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_panoptium_v1_events_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_panoptium_v1_events_proto_rawDescGZIP(), []int{0}
}

// EventSource identifies the component that emitted the event.
type EventSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// component is the emitting subsystem (e.g., "extproc", "ebpf", "policy-engine", "controller").
	Component string `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	// instance is the specific instance identifier (e.g., pod name).
	Instance string `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	// version is the software version of the emitting component.
	Version       string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventSource) Reset() {
	*x = EventSource{}
	mi := &file_panoptium_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSource) ProtoMessage() {}

func (x *EventSource) ProtoReflect() protoreflect.Message {
	mi := &file_panoptium_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSource.ProtoReflect.Descriptor instead.
func (*EventSource) Descriptor() ([]byte, []int) {
	return file_panoptium_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *EventSource) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *EventSource) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *EventSource) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// AgentIdentity contains information about the agent that initiated the request.
// Identity is resolved via PodCache lookup from the source pod IP.
type AgentIdentity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pod_name is the resolved Kubernetes pod name.
	PodName string `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	// namespace is the Kubernetes namespace of the agent pod.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// labels contains the Kubernetes labels of the agent pod.
	Labels map[string]string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// auth_type indicates how the agent was authenticated.
	// Deprecated: retained for wire compatibility; new events use confidence instead.
	AuthType string `protobuf:"bytes,4,opt,name=auth_type,json=authType,proto3" json:"auth_type,omitempty"`
	// auth_id is the primary agent identifier.
	// Deprecated: retained for wire compatibility; new events use pod_name as the ID.
	AuthId string `protobuf:"bytes,5,opt,name=auth_id,json=authId,proto3" json:"auth_id,omitempty"`
	// source_ip is the source pod IP used for Kubernetes-native identity resolution.
	SourceIp string `protobuf:"bytes,6,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	// confidence indicates the reliability of the identity resolution.
	// "high" = resolved from PodCache, "medium" = partially resolved, "low" = unknown.
	Confidence string `protobuf:"bytes,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// pod_uid is the Kubernetes pod UID for unambiguous pod identification.
	PodUid        string `protobuf:"bytes,8,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentIdentity) Reset() {
	*x = AgentIdentity{}
	mi := &file_panoptium_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentIdentity) ProtoMessage() {}

func (x *AgentIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_panoptium_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentIdentity.ProtoReflect.Descriptor instead.
func (*AgentIdentity) Descriptor() ([]byte, []int) {
	return file_panoptium_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *AgentIdentity) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *AgentIdentity) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AgentIdentity) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *AgentIdentity) GetAuthType() string {
	if x != nil {
		return x.AuthType
	}
	return ""
}

func (x *AgentIdentity) GetAuthId() string {
	if x != nil {
		return x.AuthId
	}
	return ""
}

func (x *AgentIdentity) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *AgentIdentity) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *AgentIdentity) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

// PanoptiumEvent is the core event envelope for all Panoptium telemetry.
// Every event flowing through the event bus is wrapped in this message.
type PanoptiumEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is a ULID-based unique event identifier.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// timestamp is the event creation time with nanosecond precision.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// trace_id is the W3C Trace Context trace ID (16 bytes).
	TraceId []byte `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// span_id is the W3C Trace Context span ID (8 bytes).
	SpanId []byte `protobuf:"bytes,4,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	// parent_span_id is the parent span for correlation (8 bytes).
	ParentSpanId []byte `protobuf:"bytes,5,opt,name=parent_span_id,json=parentSpanId,proto3" json:"parent_span_id,omitempty"`
	// source identifies the component that emitted this event.
	Source *EventSource `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	// agent contains the resolved agent identity.
	Agent *AgentIdentity `protobuf:"bytes,7,opt,name=agent,proto3" json:"agent,omitempty"`
	// category is the event category (e.g., "syscall", "network", "llm").
	Category string `protobuf:"bytes,8,opt,name=category,proto3" json:"category,omitempty"`
	// subcategory is the event subcategory (e.g., "execve", "connect", "request.start").
	Subcategory string `protobuf:"bytes,9,opt,name=subcategory,proto3" json:"subcategory,omitempty"`
	// severity is the event severity level.
	Severity Severity `protobuf:"varint,10,opt,name=severity,proto3,enum=panoptium.v1.Severity" json:"severity,omitempty"`
	// payload contains the typed event data per category.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*PanoptiumEvent_SyscallEvent
	//	*PanoptiumEvent_NetworkEvent
	//	*PanoptiumEvent_ProtocolEvent
	//	*PanoptiumEvent_LlmStreamEvent
	//	*PanoptiumEvent_PolicyEvent
	//	*PanoptiumEvent_LifecycleEvent
	Payload       isPanoptiumEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PanoptiumEvent) Reset() {
	*x = PanoptiumEvent{}
	mi := &file_panoptium_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PanoptiumEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanoptiumEvent) ProtoMessage() {}

func (x *PanoptiumEvent) ProtoReflect() protoreflect.Message {
	mi := &file_panoptium_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanoptiumEvent.ProtoReflect.Descriptor instead.
func (*PanoptiumEvent) Descriptor() ([]byte, []int) {
	return file_panoptium_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *PanoptiumEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PanoptiumEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *PanoptiumEvent) GetTraceId() []byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

func (x *PanoptiumEvent) GetSpanId() []byte {
	if x != nil {
		return x.SpanId
	}
	return nil
}

func (x *PanoptiumEvent) GetParentSpanId() []byte {
	if x != nil {
		return x.ParentSpanId
	}
	return nil
}

func (x *PanoptiumEvent) GetSource() *EventSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *PanoptiumEvent) GetAgent() *AgentIdentity {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *PanoptiumEvent) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *PanoptiumEvent) GetSubcategory() string {
	if x != nil {
		return x.Subcategory
	}
	return ""
}

func (x *PanoptiumEvent) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_INFO
}

func (x *PanoptiumEvent) GetPayload() isPanoptiumEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PanoptiumEvent) GetSyscallEvent() *SyscallEvent {
	if x != nil {
		if x, ok := x.Payload.(*PanoptiumEvent_SyscallEvent); ok {
			return x.SyscallEvent
		}
	}
	return nil
}

func (x *PanoptiumEvent) GetNetworkEvent() *NetworkEvent {
	if x != nil {
		if x, ok := x.Payload.(*PanoptiumEvent_NetworkEvent); ok {
			return x.NetworkEvent
		}
	}
	return nil
}

func (x *PanoptiumEvent) GetProtocolEvent() *ProtocolEvent {
	if x != nil {
		if x, ok := x.Payload.(*PanoptiumEvent_ProtocolEvent); ok {
			return x.ProtocolEvent
		}
	}
	return nil
}

func (x *PanoptiumEvent) GetLlmStreamEvent() *LLMStreamEvent {
	if x != nil {
		if x, ok := x.Payload.(*PanoptiumEvent_LlmStreamEvent); ok {
			return x.LlmStreamEvent
		}
	}
	return nil
}

func (x *PanoptiumEvent) GetPolicyEvent() *PolicyEvent {
	if x != nil {
		if x, ok := x.Payload.(*PanoptiumEvent_PolicyEvent); ok {
			return x.PolicyEvent
		}
	}
	return nil
}

func (x *PanoptiumEvent) GetLifecycleEvent() *LifecycleEvent {
	if x != nil {
		if x, ok := x.Payload.(*PanoptiumEvent_LifecycleEvent); ok {
			return x.LifecycleEvent
		}
	}
	return nil
}

type isPanoptiumEvent_Payload interface {
	isPanoptiumEvent_Payload()
}

type PanoptiumEvent_SyscallEvent struct {
	SyscallEvent *SyscallEvent `protobuf:"bytes,11,opt,name=syscall_event,json=syscallEvent,proto3,oneof"`
}

type PanoptiumEvent_NetworkEvent struct {
	NetworkEvent *NetworkEvent `protobuf:"bytes,12,opt,name=network_event,json=networkEvent,proto3,oneof"`
}

type PanoptiumEvent_ProtocolEvent struct {
	ProtocolEvent *ProtocolEvent `protobuf:"bytes,13,opt,name=protocol_event,json=protocolEvent,proto3,oneof"`
}

type PanoptiumEvent_LlmStreamEvent struct {
	LlmStreamEvent *LLMStreamEvent `protobuf:"bytes,14,opt,name=llm_stream_event,json=llmStreamEvent,proto3,oneof"`
}

type PanoptiumEvent_PolicyEvent struct {
	PolicyEvent *PolicyEvent `protobuf:"bytes,15,opt,name=policy_event,json=policyEvent,proto3,oneof"`
}

type PanoptiumEvent_LifecycleEvent struct {
	LifecycleEvent *LifecycleEvent `protobuf:"bytes,16,opt,name=lifecycle_event,json=lifecycleEvent,proto3,oneof"`
}

func (*PanoptiumEvent_SyscallEvent) isPanoptiumEvent_Payload() {}

func (*PanoptiumEvent_NetworkEvent) isPanoptiumEvent_Payload() {}

func (*PanoptiumEvent_ProtocolEvent) isPanoptiumEvent_Payload() {}

func (*PanoptiumEvent_LlmStreamEvent) isPanoptiumEvent_Payload() {}

func (*PanoptiumEvent_PolicyEvent) isPanoptiumEvent_Payload() {}

func (*PanoptiumEvent_LifecycleEvent) isPanoptiumEvent_Payload() {}

// SyscallEvent contains data about a system call observation.
type SyscallEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Comm          string                 `protobuf:"bytes,2,opt,name=comm,proto3" json:"comm,omitempty"`
	SyscallNr     uint32                 `protobuf:"varint,3,opt,name=syscall_nr,json=syscallNr,proto3" json:"syscall_nr,omitempty"`
	Args          []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	ReturnCode    int32                  `protobuf:"varint,5,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	CgroupId      uint64                 `protobuf:"varint,6,opt,name=cgroup_id,json=cgroupId,proto3" json:"cgroup_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyscallEvent) Reset() {
	*x = SyscallEvent{}
	mi := &file_panoptium_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyscallEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyscallEvent) ProtoMessage() {}

func (x *SyscallEvent) ProtoReflect() protoreflect.Message {
	mi := &file_panoptium_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyscallEvent.ProtoReflect.Descriptor instead.
func (*SyscallEvent) Descriptor() ([]byte, []int) {
	return file_panoptium_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *SyscallEvent) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *SyscallEvent) GetComm() string {
	if x != nil {
		return x.Comm
	}
	return ""
}

func (x *SyscallEvent) GetSyscallNr() uint32 {
	if x != nil {
		return x.SyscallNr
	}
	return 0
}

func (x *SyscallEvent) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *SyscallEvent) GetReturnCode() int32 {
	if x != nil {
		return x.ReturnCode
	}
	return 0
}

func (x *SyscallEvent) GetCgroupId() uint64 {
	if x != nil {
		return x.CgroupId
	}
	return 0
}

// NetworkEvent contains data about a network connection observation.
type NetworkEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcIp         string                 `protobuf:"bytes,1,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	SrcPort       uint32                 `protobuf:"varint,2,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstIp         string                 `protobuf:"bytes,3,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	DstPort       uint32                 `protobuf:"varint,4,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	BytesTx       uint64                 `protobuf:"varint,6,opt,name=bytes_tx,json=bytesTx,proto3" json:"bytes_tx,omitempty"`
	BytesRx       uint64                 `protobuf:"varint,7,opt,name=bytes_rx,json=bytesRx,proto3" json:"bytes_rx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkEvent) Reset() {
	*x = NetworkEvent{}
	mi := &file_panoptium_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkEvent) ProtoMessage() {}

func (x *NetworkEvent) ProtoReflect() protoreflect.Message {
	mi := &file_panoptium_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkEvent.ProtoReflect.Descriptor instead.
func (*NetworkEvent) Descriptor() ([]byte, []int) {
	return file_panoptium_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkEvent) GetSrcIp() string {
	if x != nil {
		return x.SrcIp
	}
	return ""
}

func (x *NetworkEvent) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *NetworkEvent) GetDstIp() string {
	if x != nil {
		return x.DstIp
	}
	return ""
}

func (x *NetworkEvent) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *NetworkEvent) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *NetworkEvent) GetBytesTx() uint64 {
	if x != nil {
		return x.BytesTx
	}
	return 0
}

func (x *NetworkEvent) GetBytesRx() uint64 {
	if x != nil {
		return x.BytesRx
	}
	return 0
}

// ProtocolEvent contains data about an application protocol observation.
type ProtocolEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HttpMethod    string                 `protobuf:"bytes,1,opt,name=http_method,json=httpMethod,proto3" json:"http_method,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StatusCode    int32                  `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ContentType   string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolEvent) Reset() {
	*x = ProtocolEvent{}
	mi := &file_panoptium_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolEvent) ProtoMessage() {}

func (x *ProtocolEvent) ProtoReflect() protoreflect.Message {
	mi := &file_panoptium_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolEvent.ProtoReflect.Descriptor instead.
func (*ProtocolEvent) Descriptor() ([]byte, []int) {
	return file_panoptium_v1_events_proto_rawDescGZIP(), []int{5}
}

func (x *ProtocolEvent) GetHttpMethod() string {
	if x != nil {
		return x.HttpMethod
	}
	return ""
}

func (x *ProtocolEvent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ProtocolEvent) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ProtocolEvent) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ProtocolEvent) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

// LLMStreamEvent contains data about an LLM request/response observation.
type LLMStreamEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Messages      []string               `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	Tokens        int32                  `protobuf:"varint,4,opt,name=tokens,proto3" json:"tokens,omitempty"`
	TtftMs        float64                `protobuf:"fixed64,5,opt,name=ttft_ms,json=ttftMs,proto3" json:"ttft_ms,omitempty"`
	FinishReason  string                 `protobuf:"bytes,6,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	ToolCalls     []*ToolCall            `protobuf:"bytes,7,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMStreamEvent) Reset() {
	*x = LLMStreamEvent{}
	mi := &file_panoptium_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMStreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMStreamEvent) ProtoMessage() {}

func (x *LLMStreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_panoptium_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMStreamEvent.ProtoReflect.Descriptor instead.
func (*LLMStreamEvent) Descriptor() ([]byte, []int) {
	return file_panoptium_v1_events_proto_rawDescGZIP(), []int{6}
}

func (x *LLMStreamEvent) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *LLMStreamEvent) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LLMStreamEvent) GetMessages() []string {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *LLMStreamEvent) GetTokens() int32 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

func (x *LLMStreamEvent) GetTtftMs() float64 {
	if x != nil {
		return x.TtftMs
	}
	return 0
}

func (x *LLMStreamEvent) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *LLMStreamEvent) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

// ToolCall represents a tool invocation within an LLM response.
type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     string                 `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_panoptium_v1_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_panoptium_v1_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_panoptium_v1_events_proto_rawDescGZIP(), []int{7}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

// PolicyEvent contains data about a policy evaluation or violation.
type PolicyEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PolicyName      string                 `protobuf:"bytes,1,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
	RuleIndex       int32                  `protobuf:"varint,2,opt,name=rule_index,json=ruleIndex,proto3" json:"rule_index,omitempty"`
	Action          string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	MatchDetails    string                 `protobuf:"bytes,4,opt,name=match_details,json=matchDetails,proto3" json:"match_details,omitempty"`
	EnforcementMode string                 `protobuf:"bytes,5,opt,name=enforcement_mode,json=enforcementMode,proto3" json:"enforcement_mode,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PolicyEvent) Reset() {
	*x = PolicyEvent{}
	mi := &file_panoptium_v1_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyEvent) ProtoMessage() {}

func (x *PolicyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_panoptium_v1_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyEvent.ProtoReflect.Descriptor instead.
func (*PolicyEvent) Descriptor() ([]byte, []int) {
	return file_panoptium_v1_events_proto_rawDescGZIP(), []int{8}
}

func (x *PolicyEvent) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

func (x *PolicyEvent) GetRuleIndex() int32 {
	if x != nil {
		return x.RuleIndex
	}
	return 0
}

func (x *PolicyEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PolicyEvent) GetMatchDetails() string {
	if x != nil {
		return x.MatchDetails
	}
	return ""
}

func (x *PolicyEvent) GetEnforcementMode() string {
	if x != nil {
		return x.EnforcementMode
	}
	return ""
}

// LifecycleEvent contains data about a pod lifecycle observation.
type LifecycleEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PodName           string                 `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Namespace         string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Phase             string                 `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	ContainerStatuses []*ContainerStatus     `protobuf:"bytes,4,rep,name=container_statuses,json=containerStatuses,proto3" json:"container_statuses,omitempty"`
	RestartCount      int32                  `protobuf:"varint,5,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LifecycleEvent) Reset() {
	*x = LifecycleEvent{}
	mi := &file_panoptium_v1_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifecycleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleEvent) ProtoMessage() {}

func (x *LifecycleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_panoptium_v1_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleEvent.ProtoReflect.Descriptor instead.
func (*LifecycleEvent) Descriptor() ([]byte, []int) {
	return file_panoptium_v1_events_proto_rawDescGZIP(), []int{9}
}

func (x *LifecycleEvent) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *LifecycleEvent) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *LifecycleEvent) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *LifecycleEvent) GetContainerStatuses() []*ContainerStatus {
	if x != nil {
		return x.ContainerStatuses
	}
	return nil
}

func (x *LifecycleEvent) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

// ContainerStatus represents the status of a container in a pod.
type ContainerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Ready         bool                   `protobuf:"varint,3,opt,name=ready,proto3" json:"ready,omitempty"`
	RestartCount  int32                  `protobuf:"varint,4,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerStatus) Reset() {
	*x = ContainerStatus{}
	mi := &file_panoptium_v1_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerStatus) ProtoMessage() {}

func (x *ContainerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_panoptium_v1_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerStatus.ProtoReflect.Descriptor instead.
func (*ContainerStatus) Descriptor() ([]byte, []int) {
	return file_panoptium_v1_events_proto_rawDescGZIP(), []int{10}
}

func (x *ContainerStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ContainerStatus) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *ContainerStatus) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

var File_panoptium_v1_events_proto protoreflect.FileDescriptor

const file_panoptium_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x19panoptium/v1/events.proto\x12\fpanoptium.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"a\n" +
	"\vEventSource\x12\x1c\n" +
	"\tcomponent\x18\x01 \x01(\tR\tcomponent\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\x97\x02\n" +
	"\rAgentIdentity\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12?\n" +
	"\x06labels\x18\x03 \x03(\v2'.panoptium.v1.AgentIdentity.LabelsEntryR\x06labels\x12\x1b\n" +
	"\tauth_type\x18\x04 \x01(\tR\bauthType\x12\x17\n" +
	"\aauth_id\x18\x05 \x01(\tR\x06authId\x12\x1b\n" +
	"\tsource_ip\x18\x06 \x01(\tR\bsourceIp\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb6\x06\n" +
	"\x0ePanoptiumEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\fR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x04 \x01(\fR\x06spanId\x12$\n" +
	"\x0eparent_span_id\x18\x05 \x01(\fR\fparentSpanId\x121\n" +
	"\x06source\x18\x06 \x01(\v2\x19.panoptium.v1.EventSourceR\x06source\x121\n" +
	"\x05agent\x18\a \x01(\v2\x1b.panoptium.v1.AgentIdentityR\x05agent\x12\x1a\n" +
	"\bcategory\x18\b \x01(\tR\bcategory\x12 \n" +
	"\vsubcategory\x18\t \x01(\tR\vsubcategory\x122\n" +
	"\bseverity\x18\n" +
	" \x01(\x0e2\x16.panoptium.v1.SeverityR\bseverity\x12A\n" +
	"\rsyscall_event\x18\v \x01(\v2\x1a.panoptium.v1.SyscallEventH\x00R\fsyscallEvent\x12A\n" +
	"\rnetwork_event\x18\f \x01(\v2\x1a.panoptium.v1.NetworkEventH\x00R\fnetworkEvent\x12D\n" +
	"\x0eprotocol_event\x18\r \x01(\v2\x1b.panoptium.v1.ProtocolEventH\x00R\rprotocolEvent\x12H\n" +
	"\x10llm_stream_event\x18\x0e \x01(\v2\x1c.panoptium.v1.LLMStreamEventH\x00R\x0ellmStreamEvent\x12>\n" +
	"\fpolicy_event\x18\x0f \x01(\v2\x19.panoptium.v1.PolicyEventH\x00R\vpolicyEvent\x12G\n" +
	"\x0flifecycle_event\x18\x10 \x01(\v2\x1c.panoptium.v1.LifecycleEventH\x00R\x0elifecycleEventB\t\n" +
	"\apayload\"\xa5\x01\n" +
	"\fSyscallEvent\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x12\n" +
	"\x04comm\x18\x02 \x01(\tR\x04comm\x12\x1d\n" +
	"\n" +
	"syscall_nr\x18\x03 \x01(\rR\tsyscallNr\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x12\x1f\n" +
	"\vreturn_code\x18\x05 \x01(\x05R\n" +
	"returnCode\x12\x1b\n" +
	"\tcgroup_id\x18\x06 \x01(\x04R\bcgroupId\"\xc4\x01\n" +
	"\fNetworkEvent\x12\x15\n" +
	"\x06src_ip\x18\x01 \x01(\tR\x05srcIp\x12\x19\n" +
	"\bsrc_port\x18\x02 \x01(\rR\asrcPort\x12\x15\n" +
	"\x06dst_ip\x18\x03 \x01(\tR\x05dstIp\x12\x19\n" +
	"\bdst_port\x18\x04 \x01(\rR\adstPort\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\tR\bprotocol\x12\x19\n" +
	"\bbytes_tx\x18\x06 \x01(\x04R\abytesTx\x12\x19\n" +
	"\bbytes_rx\x18\a \x01(\x04R\abytesRx\"\x86\x02\n" +
	"\rProtocolEvent\x12\x1f\n" +
	"\vhttp_method\x18\x01 \x01(\tR\n" +
	"httpMethod\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12B\n" +
	"\aheaders\x18\x03 \x03(\v2(.panoptium.v1.ProtocolEvent.HeadersEntryR\aheaders\x12\x1f\n" +
	"\vstatus_code\x18\x04 \x01(\x05R\n" +
	"statusCode\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xeb\x01\n" +
	"\x0eLLMStreamEvent\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x1a\n" +
	"\bmessages\x18\x03 \x03(\tR\bmessages\x12\x16\n" +
	"\x06tokens\x18\x04 \x01(\x05R\x06tokens\x12\x17\n" +
	"\attft_ms\x18\x05 \x01(\x01R\x06ttftMs\x12#\n" +
	"\rfinish_reason\x18\x06 \x01(\tR\ffinishReason\x125\n" +
	"\n" +
	"tool_calls\x18\a \x03(\v2\x16.panoptium.v1.ToolCallR\ttoolCalls\"L\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x03 \x01(\tR\targuments\"\xb5\x01\n" +
	"\vPolicyEvent\x12\x1f\n" +
	"\vpolicy_name\x18\x01 \x01(\tR\n" +
	"policyName\x12\x1d\n" +
	"\n" +
	"rule_index\x18\x02 \x01(\x05R\truleIndex\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12#\n" +
	"\rmatch_details\x18\x04 \x01(\tR\fmatchDetails\x12)\n" +
	"\x10enforcement_mode\x18\x05 \x01(\tR\x0fenforcementMode\"\xd2\x01\n" +
	"\x0eLifecycleEvent\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x12L\n" +
	"\x12container_statuses\x18\x04 \x03(\v2\x1d.panoptium.v1.ContainerStatusR\x11containerStatuses\x12#\n" +
	"\rrestart_count\x18\x05 \x01(\x05R\frestartCount\"v\n" +
	"\x0fContainerStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x14\n" +
	"\x05ready\x18\x03 \x01(\bR\x05ready\x12#\n" +
	"\rrestart_count\x18\x04 \x01(\x05R\frestartCount*A\n" +
	"\bSeverity\x12\b\n" +
	"\x04INFO\x10\x00\x12\a\n" +
	"\x03LOW\x10\x01\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x02\x12\b\n" +
	"\x04HIGH\x10\x03\x12\f\n" +
	"\bCRITICAL\x10\x04B0Z.github.com/panoptium/panoptium/pkg/eventbus/pbb\x06proto3"

var (
	file_panoptium_v1_events_proto_rawDescOnce sync.Once
	file_panoptium_v1_events_proto_rawDescData []byte
)

func file_panoptium_v1_events_proto_rawDescGZIP() []byte {
	file_panoptium_v1_events_proto_rawDescOnce.Do(func() {
		file_panoptium_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_panoptium_v1_events_proto_rawDesc), len(file_panoptium_v1_events_proto_rawDesc)))
	})
	return file_panoptium_v1_events_proto_rawDescData
}

var file_panoptium_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_panoptium_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_panoptium_v1_events_proto_goTypes = []any{
	(Severity)(0),                 // 0: panoptium.v1.Severity
	(*EventSource)(nil),           // 1: panoptium.v1.EventSource
	(*AgentIdentity)(nil),         // 2: panoptium.v1.AgentIdentity
	(*PanoptiumEvent)(nil),        // 3: panoptium.v1.PanoptiumEvent
	(*SyscallEvent)(nil),          // 4: panoptium.v1.SyscallEvent
	(*NetworkEvent)(nil),          // 5: panoptium.v1.NetworkEvent
	(*ProtocolEvent)(nil),         // 6: panoptium.v1.ProtocolEvent
	(*LLMStreamEvent)(nil),        // 7: panoptium.v1.LLMStreamEvent
	(*ToolCall)(nil),              // 8: panoptium.v1.ToolCall
	(*PolicyEvent)(nil),           // 9: panoptium.v1.PolicyEvent
	(*LifecycleEvent)(nil),        // 10: panoptium.v1.LifecycleEvent
	(*ContainerStatus)(nil),       // 11: panoptium.v1.ContainerStatus
	nil,                           // 12: panoptium.v1.AgentIdentity.LabelsEntry
	nil,                           // 13: panoptium.v1.ProtocolEvent.HeadersEntry
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_panoptium_v1_events_proto_depIdxs = []int32{
	12, // 0: panoptium.v1.AgentIdentity.labels:type_name -> panoptium.v1.AgentIdentity.LabelsEntry
	14, // 1: panoptium.v1.PanoptiumEvent.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 2: panoptium.v1.PanoptiumEvent.source:type_name -> panoptium.v1.EventSource
	2,  // 3: panoptium.v1.PanoptiumEvent.agent:type_name -> panoptium.v1.AgentIdentity
	0,  // 4: panoptium.v1.PanoptiumEvent.severity:type_name -> panoptium.v1.Severity
	4,  // 5: panoptium.v1.PanoptiumEvent.syscall_event:type_name -> panoptium.v1.SyscallEvent
	5,  // 6: panoptium.v1.PanoptiumEvent.network_event:type_name -> panoptium.v1.NetworkEvent
	6,  // 7: panoptium.v1.PanoptiumEvent.protocol_event:type_name -> panoptium.v1.ProtocolEvent
	7,  // 8: panoptium.v1.PanoptiumEvent.llm_stream_event:type_name -> panoptium.v1.LLMStreamEvent
	9,  // 9: panoptium.v1.PanoptiumEvent.policy_event:type_name -> panoptium.v1.PolicyEvent
	10, // 10: panoptium.v1.PanoptiumEvent.lifecycle_event:type_name -> panoptium.v1.LifecycleEvent
	13, // 11: panoptium.v1.ProtocolEvent.headers:type_name -> panoptium.v1.ProtocolEvent.HeadersEntry
	8,  // 12: panoptium.v1.LLMStreamEvent.tool_calls:type_name -> panoptium.v1.ToolCall
	11, // 13: panoptium.v1.LifecycleEvent.container_statuses:type_name -> panoptium.v1.ContainerStatus
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_panoptium_v1_events_proto_init() }
func file_panoptium_v1_events_proto_init() {
	if File_panoptium_v1_events_proto != nil {
		return
	}
	file_panoptium_v1_events_proto_msgTypes[2].OneofWrappers = []any{
		(*PanoptiumEvent_SyscallEvent)(nil),
		(*PanoptiumEvent_NetworkEvent)(nil),
		(*PanoptiumEvent_ProtocolEvent)(nil),
		(*PanoptiumEvent_LlmStreamEvent)(nil),
		(*PanoptiumEvent_PolicyEvent)(nil),
		(*PanoptiumEvent_LifecycleEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_panoptium_v1_events_proto_rawDesc), len(file_panoptium_v1_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_panoptium_v1_events_proto_goTypes,
		DependencyIndexes: file_panoptium_v1_events_proto_depIdxs,
		EnumInfos:         file_panoptium_v1_events_proto_enumTypes,
		MessageInfos:      file_panoptium_v1_events_proto_msgTypes,
	}.Build()
	File_panoptium_v1_events_proto = out.File
	file_panoptium_v1_events_proto_goTypes = nil
	file_panoptium_v1_events_proto_depIdxs = nil
}
