apiVersion: v1
kind: Service
metadata:
  name: {{ include "panoptium.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "panoptium.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  ports:
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    {{- include "panoptium.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller-manager
